# Generated by Django 4.1.4 on 2022-12-16 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main2', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='catefory',
            new_name='category',
        ),
    ]
