# Generated by Django 4.1.4 on 2022-12-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main2', '0002_rename_catefory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='Shop2/Main2/static'),
        ),
    ]
